### ISSUE TITLE
Error on feedback channel layout

### ISSUE THREAD

**Issue by MarcHagen** [bitfocus/companion-module-epiphan-pearl#1]
/cc @pavelkudelin
https://github.com/bitfocus/companion/issues/388#issuecomment-522910992
> tested the module.
> 
> * Layout switching works
> * Recording is activated after double-clicking. Nothing happens after the first command.
> * special thanks for processing the recording feedback
> * processing of the "Change colors on chanel layout change" event causes an error (screenshot). And it is not removed anymore. Even the program rearrangement does not help.
>   ![2019-08-19 20 30 00](https://user-images.githubusercontent.com/54240249/63330963-5f409480-c33d-11e9-8a69-913e2f32c9b8.png)

So the error for the feedback is a bit vage. Could you clarify these questions?

- Because the Pearl is "quite slow" did you try pressing it once and waited a bit?
I don't have this issue at my Pearl atm.

- Have a added a extra check, but would you mind to share you're config as of this error? Then i can check what value is given when the error occurred.

**Comment by pavelkudelin** [comment]
I've reinstalled everything on the new computer. 
1. feedback is working. I get a message (on the screenshot), but only once during setup. Then it doesn't appear anymore. 
2. Starting the recording also started working the first time. It seems that the problem was in the Companion - Stream Desk connection

just in case, I'm sending out a configuration 
[pk10_full-config_20190822-1653.zip](https://github.com/bitfocus/companion-module-epiphan-pearl/files/3530739/pk10_full-config_20190822-1653.zip)

**Comment by MarcHagen** [comment]
So i have checkout you're config and that look good. The feedback issue is fixed.
