### ISSUE TITLE
[REQUEST] Epiphan Pearl: ‘Preview’ & ‘Take’ Functionality

### ISSUE THREAD

**Issue by thepeginator** [bitfocus/companion-module-epiphan-pearl#6]
The Epiphan Pearl already has basic functions for starting/ stoping streaming & recording, as well as a ‘hard take’ shot box style function for switching between presets, whereby the selected preset is taken immediately without the ability to preview.

It would be very useful to have the ability to preview presets - as you do when controlling the pearl via the web interface - and then ‘take’ that preset from preview to program as you usually would with a production switcher.

Thank you.

**Comment by MarcHagen** [comment]
Yes this would be a great feature. But it's not that simple to implement. (i think...)
I have to dig into the pearl coding to see what's happening there

**Comment by thepeginator** [comment]
Yeh I figured it probably wasn't super straight forward or you would have done it already. If it's possible to implement it would be awesome.

**Comment by MarcHagen** [comment]
So i checked out the code and stuff. But i cannot make this work. 
The preview window you have in the GUI is a client side thing. In the background it just requests a different stream from the Epiphan. 
The Epiphan doesn't have a "preview" capability. 

Like i mentioned because the preview is a client side thing in the GUI i cannot magically change that. 
So i have to disappoint you but this feature will not get implemented.

**Comment by thepeginator** [comment]
No worries, thanks for trying!
